name: Download Artifacts

on:
  push:
    branches:
      - main

jobs:
  download-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List artifacts
        id: list-artifacts
        uses: MichaelMelena/list-artifacts@v1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          run: ls -R
